Geojson generation
catalpainternational/simple_locations pull request #4
Opened 2017-04-18 03:28 UTC by joshbrooks

Adds endpoints to efficiently return geoJSON data for areas, intended for consumption by the location-map riot tag in openly.

2017-04-18 05:07 UTC, PeteCoward commented
does teh views part of this duplicate the work Sean has done in openly_geodata?

2017-04-18 05:19 UTC, joshbrooks commented
@PeteCoward @syting Not aware of such, I haven't seen any place where this is replicated but there could be if it's not been merged with master yet

2017-04-18 10:30 UTC, PeteCoward commented
https://github.com/catalpainternational/openly/blob/master/openly/openly_geodata/views.py

This is what hamutuk are using to return leaflet friendly geojson

2017-04-19 01:18 UTC, raphaelmerx requested changes

2017-04-19 01:18 UTC, raphaelmerx commented on simple_locations/models.py
> +    def bounds(self):
This defined property is unused

2017-04-19 01:18 UTC, raphaelmerx commented on simple_locations/json_views.py
> +from django.http import HttpResponse
Lots of unused imports in here

2017-04-19 01:18 UTC, raphaelmerx commented on simple_locations/json_views.py
> +    return JsonResponse(Area.geojson(area_id))
This is going to 500 if the `area_id` is invalid

2017-04-19 01:18 UTC, raphaelmerx commented on simple_locations/json_views.py
> +    return JsonResponse(Area.geojson(area_id, children=True))
May as well remove the optional argument `children` in `geojson` and call `geojson_children` from here, since the two class methods are independent.

2017-04-19 03:51 UTC, joshbrooks commented
Going to close this for now, as it's duplicating what can be returned with what Peter suggested above.

2017-04-19 03:51 UTC, closed without merging